server.port: 9101

wirequery:
  connection:
    secure: false
    host: localhost:9090
    appName: Products
    apiKey: 1/2ccfed75-9785-4ed3-a133-5ef94425cd7a
  maskSettings:
    requestHeaders:
      - accountid
      - wirequery-request-correlation-id
      - wirequery-recording-correlation-id

#wirequery:
#  connection:
#    secure: false
#    host: localhost:9090
#    appName: products
#    apiKey: 1/8229b356-8055-4cd1-9399-be4122f1c9aa # Usually this should be injected as an environment variable
#  maskSettings:
#    requestHeaders:
#      - accountid
