server.port: 9101

wirequery:
  connection:
    secure: true
    host: grpc.wirequery.io:443
    appName: products
    apiKey: 1/0df82d0b-8dca-4002-8f47-0d210ab1c734
  maskSettings:
    requestHeaders:
      - accountid

#wirequery:
#  connection:
#    secure: false
#    host: localhost:9090
#    appName: products
#    apiKey: 1/8229b356-8055-4cd1-9399-be4122f1c9aa # Usually this should be injected as an environment variable
#  maskSettings:
#    requestHeaders:
#      - accountid
