server.port: 9101

wirequery:
  connection:
    secure: true
    host: grpc.wirequery.io:443
    appName: products
    apiKey: 1/6cc07572-ea9f-468a-b6c4-fea745a4044d
  maskSettings:
    requestHeaders:
      - accountid

#wirequery:
#  connection:
#    secure: false
#    host: localhost:9090
#    appName: products
#    apiKey: 1/8229b356-8055-4cd1-9399-be4122f1c9aa # Usually this should be injected as an environment variable
#  maskSettings:
#    requestHeaders:
#      - accountid
