# Use this Docker Compose file to spin up WireQuery on your local machine.
version: '3'

services:
  reverseproxy:
    image: nginx
    ports:
      - "8090:8090"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      wirequery-backend:
        condition: service_started
      wirequery-frontend:
        condition: service_started
  wirequery-db:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  wirequery-redis:
    image: redis
    ports:
      - "16379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  wirequery-backend:
    image: ghcr.io/wirequery/wirequery-backend:latest
    ports:
      - "9090:9090"
    environment:
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://wirequery-db:5432/postgres
      WIREQUERY_REDIS_HOSTNAME: wirequery-redis
      WIREQUERY_REDIS_PORT: 6379
      WIREQUERY_DB_USER: postgres
      WIREQUERY_DB_PASSWORD: postgres
      WIREQUERY_DB_URL: jdbc:postgresql://wirequery-db:5432/postgres
      WIREQUERY_ADMIN_ENABLED: "true"
      WIREQUERY_TENANT_ID: "1"
      WIREQUERY_MULTITENANT_DISABLE: true
    depends_on:
      wirequery-redis:
        condition: service_healthy
      wirequery-db:
        condition: service_healthy
  wirequery-frontend:
    image: ghcr.io/wirequery/wirequery-frontend:latest
