server.port: 9100

wirequery:
  connection:
    secure: false
    host: localhost:9090
    appName: balance-calculator
    apiKey: 0396a1f2-4ac7-4367-bad4-b2a3558a420f    # Usually this should be injected as an environment variable
