version: '3'

services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis
    ports:
      - "6379:6379"
