version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis
    ports:
      - "6379:6379"
