server.port: 9101

wirequery:
  queries:
    - name: debit
      query: GET /transactions/{accountId} | flatMap it.responseBody | filter it.type == "DEBIT" | map it.amount > 0 | distinct
    - name: credits
      query: GET /transactions/{accountId} | flatMap it.responseBody | filter it.type == "CREDIT" | map it.amount > 0 | distinct
    - name: all
      query: GET /transactions/{accountId} | flatMap it.responseBody
    - name: currencies
      query: GET /transactions/{accountId} | flatMap it.responseBody.map(trx, trx.currency) | distinct
