server.port: 9100

wirequery:
  connection:
    secure: true
    host: grpc.wirequery.io:443
    appName: basket
    apiKey: 1/e74a706f-4443-49f9-bb6a-e6d1a762b711 # Usually this should be injected as an environment variable
  maskSettings:
    requestHeaders:
      - accountid

#wirequery:
#  connection:
#    secure: false
#    host: localhost:9090
#    appName: basket
#    apiKey: 1/a5eb574c-7420-4d9e-ae0d-67082cccad20 # Usually this should be injected as an environment variable
#  maskSettings:
#    requestHeaders:
#      - accountid
