server.port: 9100

wirequery:
  connection:
    secure: false
    host: localhost:9090
    appName: Basket
    apiKey: 1/d7c50218-bc6a-45a7-80a8-0e2a3c95d82c # Usually this should be injected as an environment variable
  maskSettings:
    requestHeaders:
      - accountid
      - wirequery-recording-correlation-id
      - wirequery-request-correlation-id

#wirequery:
#  connection:
#    secure: false
#    host: localhost:9090
#    appName: basket
#    apiKey: 1/a5eb574c-7420-4d9e-ae0d-67082cccad20 # Usually this should be injected as an environment variable
#  maskSettings:
#    requestHeaders:
#      - accountid
