on:
  pull_request_target:
jobs:
  pr-to-private-repo:
    if: github.repository == 'wirequery/wirequery'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          mkdir ~/.ssh
          echo $'${{ secrets.SSH_KEY }}' > ~/.ssh/id_rsa
          echo $'${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
          echo 'https://user:${{ secrets.GH_TOKEN }}@github.com' > ~/.git-credentials
          git config --global user.name Wouter Nederhof
          git config --global user.email wouter.nederhof@gmail.com
          docker pull olivr/copybara:latest
          docker run \
            -v ~/.ssh:/root/.ssh \
            -v ~/.gitconfig:/root/.gitconfig \
            -v ~/.git-credentials:/root/.git-credentials \
            -v "$(pwd)":/usr/src/app \
            -e COPYBARA_CONFIG=/usr/src/app/copy.bara.sky \
            -e COPYBARA_WORKFLOW=pr \
            -e COPYBARA_SOURCEREF=${{ github.event.number }} \
            -i olivr/copybara copybara
        shell: bash
