name: Test FE and BE
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run Gradle test on WireQuery Java Core SDK
        working-directory: ./sdk/jvm/wirequery-java-core
        run: ./gradlew test && ./gradlew publishToMavenLocal --no-daemon
      - name: Run Gradle test on WireQuery Spring 5 SDK
        working-directory: ./sdk/jvm/wirequery-spring-5
        run: ./gradlew test && ./gradlew publishToMavenLocal --no-daemon
      - name: Run Gradle test on WireQuery Spring 6 SDK
        working-directory: ./sdk/jvm/wirequery-spring-6
        run: ./gradlew test && ./gradlew publishToMavenLocal --no-daemon
      - name: Run Gradle test on WireQuery Spring 2 Starter SDK
        working-directory: ./sdk/jvm/wirequery-spring-boot-2-starter
        run: ./gradlew test && ./gradlew publishToMavenLocal --no-daemon
      - name: Run Gradle test on WireQuery Spring 3 Starter SDK
        working-directory: ./sdk/jvm/wirequery-spring-boot-3-starter
        run: ./gradlew test && ./gradlew publishToMavenLocal --no-daemon
      - name: Run Gradle test on the Transaction Example
        working-directory: ./sdk/jvm/examples/spring-boot/transactions
        run: ./gradlew build
      - name: Run Gradle build on the Balance Calculator Example
        working-directory: ./sdk/jvm/examples/spring-boot/balance-calculator
        run: ./gradlew build
      - name: Run Gradle build on Wirequery's manager-server
        working-directory: ./wirequery/manager-server
        run: ./gradlew test
      - name: Run Gradle build on Wirequery's manager-web
        working-directory: ./wirequery/manager-web
        run: ./gradlew test
